### ISSUE TITLE
[scrDataTLPiglands1.txt]

### ISSUE THREAD

**Issue by rao-donut** [rao-donut/tribal-hunter-translate-ja#13]

**Comment by TooSquare** [comment]
ストーリーの部分を書きました！

**Comment by rao-donut** [comment]
ありがとうございます！

**Comment by rao-donut** [comment]
- v0.0.3 時点（311文中303文翻訳完了）
  [out-303-311.csv](https://github.com/rao-donut/tribal-hunter-translate-ja/files/6686236/out-303-311.csv)
