### ISSUE TITLE
[scrDataTV.txt]

### ISSUE THREAD

**Issue by rao-donut** [rao-donut/tribal-hunter-translate-ja#16]

**Comment by FukuraMukuryu** [comment]
お疲れ様です。
次の翻訳作業として［scrDateTV.txt］の翻訳を始めても大丈夫でしょうか？

**Comment by FukuraMukuryu** [comment]
すみません、一応翻訳が完成したのでリクエスト送信しました。

**Comment by rao-donut** [comment]
@FukuraMukuryu 確認遅れてすみません。内容問題なさそうでしたのでクローズさせていただきます！

**Comment by FukuraMukuryu** [comment]
了解です。ありがとうございます。
