### ISSUE TITLE
[scrDataTriggerPiglands1.txt]

### ISSUE THREAD

**Issue by rao-donut** [rao-donut/tribal-hunter-translate-ja#24]

**Comment by FukuraMukuryu** [comment]
お疲れ様です。
次は、この［scrDataTriggerPiglands1.txt］の翻訳作業に取り掛かります。

**Comment by rao-donut** [comment]
ありがとうございます！

**Comment by TooSquare** [comment]
序盤のストーリー部分を翻訳しました！

**Comment by rao-donut** [comment]
@TooSquare 
ありがとうございます！　変更は反映済みです。

@FukuraMukuryu 
こちらの作業がコンフリクトする可能性がございますので、現在の作業ブランチをrebaseすることをおすすめします！

**Comment by FukuraMukuryu** [comment]
@rao-donut 
了解しました。

**Comment by FukuraMukuryu** [comment]
@TooSquare 
『ScrDataTriggerPiglands1.txt』の翻訳が自分の翻訳した箇所よりかなり進んでいるみたいなので、残りの翻訳もそちらの方にに任せてしまっても大丈夫でしょうか？

**Comment by TooSquare** [comment]
@FukuraMukuryu 
わかりました。頑張ります。

**Comment by rao-donut** [comment]
翻訳完了のため、クローズします。
