### ISSUE TITLE
[scrDataTriggerSlime.txt]

### ISSUE THREAD

**Issue by rao-donut** [rao-donut/tribal-hunter-translate-ja#25]

**Comment by TooSquare** [comment]
翻訳しました！スライムキングの口調はこれで大丈夫でしょうか？

**Comment by rao-donut** [comment]
@TooSquare 
ありがとうございます！
スライムキングの一人称は変更する可能性があります。

**Comment by rao-donut** [comment]
たしかによさそうですね！
印象はありそうですが朕という自称は中国のような文化が散らばっている場面以外だともしかしたら浮いてしまう可能性があります。

こちらのファイルの翻訳は完了しましたので、一旦クローズとさせていただきます！
