### ISSUE TITLE
[scrDataMaps.txt]

### ISSUE THREAD

**Issue by rao-donut** [rao-donut/tribal-hunter-translate-ja#4]

**Comment by FukuraMukuryu** [comment]
### 翻訳作業への参加申し込み
初めましてRAOさん、ふっくら無垢竜と申します。
［scrDataMaps.txt］の翻訳のお手伝いをさせていただきたいのですが、可能でしょうか？

**Comment by rao-donut** [comment]
@FukuraMukuryu 
はじめまして！

翻訳は誰でも参加可能となっております。
翻訳の進め方は[こちら](https://github.com/rao-donut/tribal-hunter-translate-ja#tribal-hunter-translate-ja)を参照してください。何かわからないことがございましたら、遠慮なくお聞きください。

**Comment by FukuraMukuryu** [comment]
[scrDataMaps.txt]の翻訳がひとまず完了しました！

**Comment by rao-donut** [comment]
@FukuraMukuryu ありがとうございます！　確認させていただきます。
