### ISSUE TITLE
[scrDataNPCchat.txt]

### ISSUE THREAD

**Issue by rao-donut** [rao-donut/tribal-hunter-translate-ja#5]

**Comment by TooSquare** [comment]
ゲーム開始時の熊さんのセリフ書きました！

**Comment by rao-donut** [comment]
@TooSquare ありがとうございますー！

**Comment by rao-donut** [comment]
- v0.0.3 時点（309文中159文翻訳完了）
  [out-160-310.csv](https://github.com/rao-donut/tribal-hunter-translate-ja/files/6686271/out-160-310.csv)
